source :rubygems

# PostgreSQL driver
gem 'pg'

# Sinatra driver
gem 'sinatra'
gem 'sinatra-contrib'

# Use Thin for our web server
gem 'thin'

gem 'activesupport'
gem "activerecord", ">= 5.2.4.5"

gem 'rake'

gem 'shotgun'

group :test do
  gem 'faker'
  gem 'rspec'
end
